name: test
on:
  push:
    paths:
      - '**.tsx?'
      - 'package.json'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Runs tests
      run: |
        npm install
        npm test